services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learn_react
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
